remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: A Plugin-based Paradigm for Practical Vehicle Road Cooperative Perception
description: Jiaru Zhong, Chao Sun, Yungang Lan, Haibao Yu, Jiahui Xu, Tianyi Zhu, Chao Yue
show_downloads: false
